# Generated by Django 5.0.6 on 2024-06-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpatient', '0003_patient_chief_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
