# Generated by Django 5.0.6 on 2024-07-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpatient', '0006_diagnosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
