# Generated by Django 5.0.6 on 2024-07-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpatient', '0008_remove_patient_description_patient_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='background',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='family_history',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lifestyle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='recent_interactions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
