# Generated by Django 5.0.6 on 2024-07-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpatient', '0009_alter_patient_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Tagalog', 'Tagalog'), ('Taglish', 'Taglish')], max_length=7, null=True),
        ),
    ]
