# Generated by Django 5.0.6 on 2024-09-02 06:42

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpatient', '0011_alter_patient_age_alter_patient_chief_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ac',
            field=models.FloatField(blank=True, help_text='in cm', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='adaptive_fine_motor_developmental_milestones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='additional_details_regarding_context_including_ethical_considerations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='additional_details_regarding_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='affect',
            field=models.CharField(blank=True, choices=[('Broad', 'Broad'), ('Flat', 'Flat'), ('Blunted', 'Blunted'), ('Restricted', 'Restricted'), ('Appropriate', 'Appropriate'), ('Inappropriate', 'Inappropriate')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='annual_family_income',
            field=models.CharField(blank=True, choices=[('< 50k', '< 50k'), ('50k - 100k', '50k - 100k'), ('100k - 200k', '100k - 200k'), ('200k - 300k', '200k - 300k'), ('> 300k', '> 300k')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='appliances',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Radio', 'Radio'), ('TV', 'TV'), ('Refrigerator', 'Refrigerator')], max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='attended_by_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='attended_by_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='attending_physician_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='attending_physician_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='attention_span',
            field=models.CharField(blank=True, choices=[('Intact', 'Intact'), ('Deficient', 'Deficient')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='attention_span_notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='attitude_towards_examiner',
            field=models.CharField(blank=True, choices=[('Cooperative', 'Cooperative'), ('Uncooperative', 'Uncooperative')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='basis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bp_diastolic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bp_systolic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='breastfed_till',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='burden_of_illness_community_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='calculation',
            field=models.CharField(blank=True, choices=[('Intact', 'Intact'), ('Deficient', 'Deficient')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='calculation_notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cancer_site_if_any',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cardiovascular',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Palpitations', 'Palpitations'), ('Chest Pains', 'Chest Pains'), ('Syncope', 'Syncope'), ('Orthopnea', 'Orthopnea')], max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cc',
            field=models.FloatField(blank=True, help_text='in cm', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cerebellars',
            field=models.CharField(blank=True, help_text='Indicate FTNT, rebound, rapid alternating hand movements, heel-to-knee', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='coitarche',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='complete_immunizations',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DPT/Polio', 'DPT/Polio'), ('HIB', 'HIB'), ('Hepatitis B', 'Hepatitis B'), ('MMR', 'MMR'), ('Measles', 'Measles'), ('Varicella', 'Varicella'), ('Pneumococcal', 'Pneumococcal'), ('Influenza', 'Influenza'), ('Hepatitis A', 'Hepatitis A')], max_length=82, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='concerns_regarding_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='consciousness',
            field=models.CharField(blank=True, choices=[('Awake', 'Awake'), ('Drowsy', 'Drowsy'), ('Stupor', 'Stupor'), ('Coma', 'Coma')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='corneals',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_diet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='delivered_via',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnostic_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dpt_or_polio_doses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='drugs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dwelling_type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='endocrine',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Excessive Sweating', 'Excessive Sweating'), ('Heat Intolerance', 'Heat Intolerance'), ('Polyuria', 'Polyuria'), ('Excessive Thirst', 'Excessive Thirst'), ('Cold Intolerance', 'Cold Intolerance')], max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='facial_muscles_bulk_and_strength_vii',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='facilitating_community_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_allergies',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_cancer_site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_cardiovascular_disease',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_relationship_to_cancer_patient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_medical_history',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Tuberculosis', 'Tuberculosis'), ('Asthma', 'Asthma'), ('Psychiatric Consult', 'Psychiatric Consult'), ('Diabetes', 'Diabetes'), ('Cardiovascular Disease', 'Cardiovascular Disease'), ('Cancer', 'Cancer'), ('Allergies', 'Allergies')], max_length=88, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='food_allergy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='formula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fund_of_information',
            field=models.CharField(blank=True, choices=[('Intact', 'Intact'), ('Deficient', 'Deficient')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fund_of_information_notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='g_mother',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gag_reflex_ix_x',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Not Normal', 'Not Normal')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gag_reflex_notes_ix_x',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gait_and_posture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gastrointestinal',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nausea', 'Nausea'), ('Vomiting', 'Vomiting'), ('Dysphagia', 'Dysphagia'), ('Heartburn', 'Heartburn'), ('Change in Bowel Habits', 'Change in Bowel Habits'), ('Rectal Bleeding', 'Rectal Bleeding'), ('Jaundice', 'Jaundice')], max_length=83, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gaze',
            field=models.CharField(blank=True, choices=[('Conjugate', 'Conjugate'), ('Dysconjugate', 'Dysconjugate')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gaze_notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='general_appearance',
            field=models.CharField(blank=True, choices=[('Well Groomed', 'Well Groomed'), ('Fairly Groomed', 'Fairly Groomed'), ('Poorly Groomed', 'Poorly Groomed')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='general_behavior',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Psychomotor Retardation', 'Psychomotor Retardation'), ('Psychomotor Agitation', 'Poorly Agitation')], max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='general_coherence',
            field=models.CharField(blank=True, choices=[('Coherent', 'Coherent'), ('Incoherent', 'Incoherent')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='general_state',
            field=models.CharField(blank=True, choices=[('Alert', 'Alert'), ('Lethargic', 'Lethargic'), ('Obtunded', 'Obtunded'), ('Stuporous', 'Stuporous'), ('Comatose', 'Comatose')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='general_symptoms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fever', 'Fever'), ('Weight Gain', 'Weight Gain'), ('Weight Loss', 'Weight Loss'), ('Weakness', 'Weakness'), ('Fatigue', 'Fatigue')], max_length=46, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='genitourinary',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nocturia', 'Nocturia'), ('Dysuria', 'Dysuria'), ('Frequency', 'Frequency'), ('Hematuria', 'Hematuria')], max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='genogram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='glasgow_coma_scale_e',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='glasgow_coma_scale_gcs',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='glasgow_coma_scale_m',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='glasgow_coma_scale_v',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='gross_motor_developmental_milestones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hc',
            field=models.FloatField(blank=True, help_text='in cm', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='heent',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Headache', 'Headache'), ('Dizziness', 'Dizziness'), ('Blurring of Vision', 'Blurring of Vision'), ('Tinnitus', 'Tinnitus'), ('Deafness', 'Deafness'), ('Nosebleeds', 'Nosebleeds'), ('Frequent Colds', 'Frequent Colds'), ('Hoarseness', 'Hoarseness'), ('Dry Mouth', 'Dry Mouth'), ('Gum Bleeding', 'Gum Bleeding'), ('Enlarged LN', 'Enlarged LN')], max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hepatitis_a_doses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hepatitis_b_doses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hib_doses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hindering_community_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='history_of_present_illness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='home',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='impact_on_family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='impulse_control',
            field=models.CharField(blank=True, choices=[('Able to Control', 'Able to Control'), ('Not Able to Control', 'Not Able to Control')], max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='influenza_doses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='informant_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='informant_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insight',
            field=models.CharField(blank=True, choices=[('Intact', 'Intact'), ('Deficient', 'Deficient')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insight_notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='intellectual_capacity_global_estimate',
            field=models.CharField(blank=True, choices=[('Above Average', 'Above Average'), ('Average', 'Average'), ('Below Average', 'Below Average')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='interest_in_issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='interval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='involuntary_movements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='judgment',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='kernigs',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='landline_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='language_developmental_milestones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='laseagues',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='level_of_influence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lmp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='masseter_and_temporalis_muscle_bulk_and_strength_v',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='measles_doses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='memory',
            field=models.CharField(blank=True, choices=[('Intact', 'Intact'), ('Deficient', 'Deficient')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='memory_notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='menarche',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='meningeals',
            field=models.CharField(blank=True, choices=[('Supple', 'Supple'), ('Rigid', 'Rigid')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='meningeals_notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mmr_doses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mood',
            field=models.CharField(blank=True, choices=[('Euthymic', 'Euthymic'), ('Dysphoric', 'Dysphoric'), ('Euphoric', 'Euphoric')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='muscle_hypertrophy_or_atrophy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='muscle_tone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='musculoskeletal_or_dermatologic',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Rashes', 'Rashes'), ('Lumps', 'Lumps'), ('Sores', 'Sores'), ('Itching', 'Itching'), ('Muscle Pains', 'Muscle Pains'), ('Joint Pains', 'Joint Pains'), ('Changes in Color', 'Changes in Color'), ('Joint Swelling', 'Joint Swelling'), ('Changes in hair/nails', 'Changes in hair/nails'), ('Gout', 'Gout')], max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Afghan', 'Afghan'), ('Albanian', 'Albanian'), ('Algerian', 'Algerian'), ('American', 'American'), ('Andorran', 'Andorran'), ('Angolan', 'Angolan'), ('Anguillan', 'Anguillan'), ('Argentine', 'Argentine'), ('Armenian', 'Armenian'), ('Australian', 'Australian'), ('Austrian', 'Austrian'), ('Azerbaijani', 'Azerbaijani'), ('Bahamian', 'Bahamian'), ('Bahraini', 'Bahraini'), ('Bangladeshi', 'Bangladeshi'), ('Barbadian', 'Barbadian'), ('Belarusian', 'Belarusian'), ('Belgian', 'Belgian'), ('Belizean', 'Belizean'), ('Beninese', 'Beninese'), ('Bermudian', 'Bermudian'), ('Bhutanese', 'Bhutanese'), ('Bolivian', 'Bolivian'), ('Botswanan', 'Botswanan'), ('Brazilian', 'Brazilian'), ('British', 'British'), ('British Virgin Islander', 'British Virgin Islander'), ('Bruneian', 'Bruneian'), ('Bulgarian', 'Bulgarian'), ('Burkinan', 'Burkinan'), ('Burmese', 'Burmese'), ('Burundian', 'Burundian'), ('Cambodian', 'Cambodian'), ('Cameroonian', 'Cameroonian'), ('Canadian', 'Canadian'), ('Cape Verdean', 'Cape Verdean'), ('Cayman Islander', 'Cayman Islander'), ('Central African', 'Central African'), ('Chadian', 'Chadian'), ('Chilean', 'Chilean'), ('Chinese', 'Chinese'), ('Citizen of Antigua and Barbuda', 'Citizen of Antigua and Barbuda'), ('Citizen of Bosnia and Herzegovina', 'Citizen of Bosnia and Herzegovina'), ('Citizen of Guinea-Bissau', 'Citizen of Guinea-Bissau'), ('Citizen of Kiribati', 'Citizen of Kiribati'), ('Citizen of Seychelles', 'Citizen of Seychelles'), ('Citizen of the Dominican Republic', 'Citizen of the Dominican Republic'), ('Citizen of Vanuatu ', 'Citizen of Vanuatu '), ('Colombian', 'Colombian'), ('Comoran', 'Comoran'), ('Congolese (Congo)', 'Congolese (Congo)'), ('Congolese (DRC)', 'Congolese (DRC)'), ('Cook Islander', 'Cook Islander'), ('Costa Rican', 'Costa Rican'), ('Croatian', 'Croatian'), ('Cuban', 'Cuban'), ('Cymraes', 'Cymraes'), ('Cymro', 'Cymro'), ('Cypriot', 'Cypriot'), ('Czech', 'Czech'), ('Danish', 'Danish'), ('Djiboutian', 'Djiboutian'), ('Dominican', 'Dominican'), ('Dutch', 'Dutch'), ('East Timorese', 'East Timorese'), ('Ecuadorean', 'Ecuadorean'), ('Egyptian', 'Egyptian'), ('Emirati', 'Emirati'), ('English', 'English'), ('Equatorial Guinean', 'Equatorial Guinean'), ('Eritrean', 'Eritrean'), ('Estonian', 'Estonian'), ('Ethiopian', 'Ethiopian'), ('Faroese', 'Faroese'), ('Fijian', 'Fijian'), ('Filipino', 'Filipino'), ('Finnish', 'Finnish'), ('French', 'French'), ('Gabonese', 'Gabonese'), ('Gambian', 'Gambian'), ('Georgian', 'Georgian'), ('German', 'German'), ('Ghanaian', 'Ghanaian'), ('Gibraltarian', 'Gibraltarian'), ('Greek', 'Greek'), ('Greenlandic', 'Greenlandic'), ('Grenadian', 'Grenadian'), ('Guamanian', 'Guamanian'), ('Guatemalan', 'Guatemalan'), ('Guinean', 'Guinean'), ('Guyanese', 'Guyanese'), ('Haitian', 'Haitian'), ('Honduran', 'Honduran'), ('Hong Konger', 'Hong Konger'), ('Hungarian', 'Hungarian'), ('Icelandic', 'Icelandic'), ('Indian', 'Indian'), ('Indonesian', 'Indonesian'), ('Iranian', 'Iranian'), ('Iraqi', 'Iraqi'), ('Irish', 'Irish'), ('Israeli', 'Israeli'), ('Italian', 'Italian'), ('Ivorian', 'Ivorian'), ('Jamaican', 'Jamaican'), ('Japanese', 'Japanese'), ('Jordanian', 'Jordanian'), ('Kazakh', 'Kazakh'), ('Kenyan', 'Kenyan'), ('Kittitian', 'Kittitian'), ('Kosovan', 'Kosovan'), ('Kuwaiti', 'Kuwaiti'), ('Kyrgyz', 'Kyrgyz'), ('Lao', 'Lao'), ('Latvian', 'Latvian'), ('Lebanese', 'Lebanese'), ('Liberian', 'Liberian'), ('Libyan', 'Libyan'), ('Liechtenstein citizen', 'Liechtenstein citizen'), ('Lithuanian', 'Lithuanian'), ('Luxembourger', 'Luxembourger'), ('Macanese', 'Macanese'), ('Macedonian', 'Macedonian'), ('Malagasy', 'Malagasy'), ('Malawian', 'Malawian'), ('Malaysian', 'Malaysian'), ('Maldivian', 'Maldivian'), ('Malian', 'Malian'), ('Maltese', 'Maltese'), ('Marshallese', 'Marshallese'), ('Martiniquais', 'Martiniquais'), ('Mauritanian', 'Mauritanian'), ('Mauritian', 'Mauritian'), ('Mexican', 'Mexican'), ('Micronesian', 'Micronesian'), ('Moldovan', 'Moldovan'), ('Monegasque', 'Monegasque'), ('Mongolian', 'Mongolian'), ('Montenegrin', 'Montenegrin'), ('Montserratian', 'Montserratian'), ('Moroccan', 'Moroccan'), ('Mosotho', 'Mosotho'), ('Mozambican', 'Mozambican'), ('Namibian', 'Namibian'), ('Nauruan', 'Nauruan'), ('Nepalese', 'Nepalese'), ('New Zealander', 'New Zealander'), ('Nicaraguan', 'Nicaraguan'), ('Nigerian', 'Nigerian'), ('Nigerien', 'Nigerien'), ('Niuean', 'Niuean'), ('North Korean', 'North Korean'), ('Northern Irish', 'Northern Irish'), ('Norwegian', 'Norwegian'), ('Omani', 'Omani'), ('Pakistani', 'Pakistani'), ('Palauan', 'Palauan'), ('Palestinian', 'Palestinian'), ('Panamanian', 'Panamanian'), ('Papua New Guinean', 'Papua New Guinean'), ('Paraguayan', 'Paraguayan'), ('Peruvian', 'Peruvian'), ('Pitcairn Islander', 'Pitcairn Islander'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Prydeinig', 'Prydeinig'), ('Puerto Rican', 'Puerto Rican'), ('Qatari', 'Qatari'), ('Romanian', 'Romanian'), ('Russian', 'Russian'), ('Rwandan', 'Rwandan'), ('Salvadorean', 'Salvadorean'), ('Sammarinese', 'Sammarinese'), ('Samoan', 'Samoan'), ('Sao Tomean', 'Sao Tomean'), ('Saudi Arabian', 'Saudi Arabian'), ('Scottish', 'Scottish'), ('Senegalese', 'Senegalese'), ('Serbian', 'Serbian'), ('Sierra Leonean', 'Sierra Leonean'), ('Singaporean', 'Singaporean'), ('Slovak', 'Slovak'), ('Slovenian', 'Slovenian'), ('Solomon Islander', 'Solomon Islander'), ('Somali', 'Somali'), ('South African', 'South African'), ('South Korean', 'South Korean'), ('South Sudanese', 'South Sudanese'), ('Spanish', 'Spanish'), ('Sri Lankan', 'Sri Lankan'), ('St Helenian', 'St Helenian'), ('St Lucian', 'St Lucian'), ('Stateless', 'Stateless'), ('Sudanese', 'Sudanese'), ('Surinamese', 'Surinamese'), ('Swazi', 'Swazi'), ('Swedish', 'Swedish'), ('Swiss', 'Swiss'), ('Syrian', 'Syrian'), ('Taiwanese', 'Taiwanese'), ('Tajik', 'Tajik'), ('Tanzanian', 'Tanzanian'), ('Thai', 'Thai'), ('Togolese', 'Togolese'), ('Tongan', 'Tongan'), ('Trinidadian', 'Trinidadian'), ('Tristanian', 'Tristanian'), ('Tunisian', 'Tunisian'), ('Turkish', 'Turkish'), ('Turkmen', 'Turkmen'), ('Turks and Caicos Islander', 'Turks and Caicos Islander'), ('Tuvaluan', 'Tuvaluan'), ('Ugandan', 'Ugandan'), ('Ukrainian', 'Ukrainian'), ('Uruguayan', 'Uruguayan'), ('Uzbek', 'Uzbek'), ('Vatican citizen', 'Vatican citizen'), ('Venezuelan', 'Venezuelan'), ('Vietnamese', 'Vietnamese'), ('Vincentian', 'Vincentian'), ('Wallisian', 'Wallisian'), ('Welsh', 'Welsh'), ('Yemeni', 'Yemeni'), ('Zambian', 'Zambian'), ('Zimbabwean', 'Zimbabwean')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='no_immunization',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DPT/Polio', 'DPT/Polio'), ('HIB', 'HIB'), ('Hepatitis B', 'Hepatitis B'), ('MMR', 'MMR'), ('Measles', 'Measles'), ('Varicella', 'Varicella'), ('Pneumococcal', 'Pneumococcal'), ('Influenza', 'Influenza'), ('Hepatitis A', 'Hepatitis A')], max_length=82, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='number_of_household_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='number_of_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nystagmus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='olfaction_i',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='orientation_person',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='orientation_place',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='orientation_time',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_cardiovascular_symptoms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_consciousness',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_endocrine_symptoms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_family_history',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_general_symptoms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_genitourinary_symptoms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_high_cortical_functions',
            field=models.CharField(blank=True, choices=[('Agnosia', 'Agnosia'), ('Apraxia', 'Apraxia')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_past_medical_history',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='p_mother',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pain_scale',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='palatal_elevation_ix_x',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Not Normal', 'Not Normal')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='palatal_elevation_notes_ix_x',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='parent_guardian_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='parent_guardian_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_medical_history',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[("Primary Koch's", "Primary Koch's"), ('Asthma', 'Asthma'), ('Diabetes', 'Diabetes'), ('Hypertension', 'Hypertension'), ('Psychiatric Consult', 'Psychiatric Consult'), ('Cancer', 'Cancer'), ('Prior Surgeries/Hospitalizations', 'Prior Surgeries/Hospitalizations'), ('Allergies', 'Allergies')], max_length=113, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='perceptual_disturbance',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Hallucinations', 'Hallucinations'), ('Depersonalization', 'Depersonalization'), ('Derealization', 'Derealization')], max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='perinatal_cx',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='personal_and_social_developmental_milestones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pertinent_beliefs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pertinent_legislation_or_policies_community_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='planning',
            field=models.CharField(blank=True, choices=[('Intact', 'Intact'), ('Deficient', 'Deficient')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='planning_notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pmp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pneumococcal_doses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='position_sense',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='preventive_measures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='prior_surgeries_or_hospitalization_dates',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='prior_surgeries_or_hospitalization_reasons',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='problem_or_impression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ptosis',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ptosis_notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='reliability',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, choices=[('Roman Catholic', 'Roman Catholic'), ('Protestant', 'Protestant'), ('Muslim', 'Muslim'), ('Iglesia ni Cristo', 'Iglesia ni Cristo'), ('Aglipay', 'Aglipay'), ('Other', 'Other')], max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='respiratory',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Dyspnea', 'Dyspnea'), ('Hemoptysis', 'Hemoptysis'), ('Cough', 'Cough'), ('Wheezing', 'Wheezing')], max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rinnes_viii',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rombergs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='schwabach_viii',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='scm_and_trapezius_contour_and_strength_notes_xi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='scm_and_trapezius_contour_and_strength_xi',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Not Normal', 'Not Normal')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexual_activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='social_and_environmental_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='source_of_income_and_dynamics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='speech',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Not Normal', 'Not Normal'), ('Dysphonia', 'Dysphonia'), ('Dysarthria', 'Dysarthria'), ('Dysprosody', 'Dysprosody'), ('Dysphasia', 'Dysphasia')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='speech_others',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='stakeholder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='stereognosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='stream_of_thought',
            field=models.CharField(blank=True, choices=[('Goal Oriented', 'Goal Oriented'), ('Looseness of Association', 'Looseness of Association'), ('Flight of Ideas', 'Flight of Ideas'), ('Paucity of Thought', 'Paucity of Thought'), ('Tangentiality', 'Tangentiality')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='substance_abuse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='swallowing_ix_x',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Not Normal', 'Not Normal')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='swallowing_notes_ix_x',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='taste_vii',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in celsius', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='term',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='therapeutic_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='thought_content',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Paranoia', 'Paranoia'), ('Grandiosity', 'Grandiosity'), ('Homicidal/Aggression', 'Homicidal/Aggression'), ('Bizarre', 'Bizarre'), ('Suicidal', 'Suicidal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='to_a',
            field=models.PositiveIntegerField(blank=True, help_text='year old', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tongue_protrusion_atrophy_fasciculations_notes_xii',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tongue_protrusion_atrophy_fasciculations_xii',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='transportation',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Car', 'Car'), ('Jeep', 'Jeep'), ('Motorcycle', 'Motorcycle')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='v1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='v2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='v3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='varicella_doses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='vibratory_sense',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weaning_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='webers_viii',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chief_complaint',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Patient_Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=50, null=True)),
                ('generic_name', models.CharField(max_length=50, null=True)),
                ('dosage', models.PositiveIntegerField(blank=True, null=True)),
                ('route', models.CharField(max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualpatient.patient')),
            ],
        ),
    ]
