# Generated by Django 5.0.6 on 2024-09-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpatient', '0012_patient_ac_patient_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='accuracy',
            field=models.TextField(blank=True, help_text='Which fields does the patient have accurate knowledge about?', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='relevance',
            field=models.TextField(blank=True, help_text="Fields relevant to the patient's current illness", null=True),
        ),
        migrations.DeleteModel(
            name='Patient_Medications',
        ),
    ]
