# Generated by Django 5.0.6 on 2024-09-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpatient', '0013_patient_accuracy_patient_medications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='other_immunizations',
            field=models.TextField(blank=True, help_text='Format: {/Immunization}, {# of Doses}; {Immunization}, {# of Doses}', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
